### ISSUE TITLE
Synch sitting instructions

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/lipbelly#16]
Text and audio instructions on how to sit do not match up. Please alter text to match the audio.

**Comment by noah10** [comment]
This is done and ready to be tested in v0.0.9.

**Comment by maramather** [comment]
Thanks. I hope Paul and/or Kaoru will take a look/listen to confirm that the text instructions on how/where to sit and the audio instructions on this now match.

**Comment by choipaul92** [comment]
Upper Lip Condition: Audio Instructions align with Written Instructions (not sure about belly condition due to condition assignment)

Instructions: "Please get into a comfortable position on a chair or on a pillow, finding a position with your back and neck upright." 

Audio: "Welcome, Please sit in a comfortable position. On chair or on a cushion. With your neck and back upright. Get comfortable."

**Comment by choipaul92** [comment]
Belly Condition: Can someone confirm that the written instructions align with the audio instructions?
Audio Instructions: “Welcome. Please sit in a comfortable position in your chair or on a pillow. Finding a position with your back and neck upright. And get comfortable”

**Comment by noah10** [comment]
This has now been superseded by #20 .
