### ISSUE TITLE
Dashboard doesn't seem to match what's shown in the app

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#17]
The app says: 20-min meditation practice(s) ($2 per practice) **$10**

The dashboard indicates: I've done **0/7 days of full training**.
<img width="1159" alt="Screen Shot 2023-10-09 at 4 08 50 PM" src="https://github.com/EmotionCognitionLab/lipbelly/assets/26439818/0e0f50a7-8559-4fbd-8d60-72903408e230">

**Comment by noah10** [comment]
This is fine. If you click on your name you'll see that it shows five days where you have done 1 20 minute session on each day (which matches with the app saying that you have earned $10, which is $2/20 minute session x 5 days with 1 20 minute session each). That means that you have done 0/7 days of full training, exactly as the dashboard says, because you need to do at least 30 minutes of training in a day for it to count as a full day.
