### ISSUE TITLE
The app gave 20-min and 10-min practices (instead of 20-min twice)

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#26]
One pilot participant in the lip condition reported that she was only given 30 min practice on her last day (first session = 20 min, second session = 10 min). I checked the emWave data, which were consistent with her report (20 min + 10 min pulse data). 

ID: bde9aded-d803-48bf-a7b0-84dda275e885
Date: 10/23

**Comment by noah10** [comment]
I'm seeing very different data. The MindBody,.sqlite file shows that she did 40 minutes on 10/22, ending just a few seconds after midnight on 10/23, and no practice at all on 10/23. The last emWave file uploaded has no practice after 10/21. If you have a more recent copy of the emWave file from her laptop please send it to me in Slack.

**Comment by noah10** [comment]
Now that I have the up-to-date files, I see 30 minutes on 10/23 in the MindBody.sqlite file and in the emWave file. The reason is that her final segment from 10/22 ended at 10 seconds after midnight on 10/23, which means that the code counted it for 10/23. Theoretically she shouldn't have been allowed to start that final session because you shouldn't be able to begin a session that you don't have time to finish before midnight. I suspect what happened is that it took ~10 seconds for the emWave session to get started after she clicked the "start" button and that is what pushed the session over into the next day. I'm going to open another bug to address that and close this one.

**Comment by noah10** [comment]
Closing in favor of #27 .
